spring.application.name=football-tournament

# SERVER
server.port=8081

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/football_tournament
spring.datasource.username=postgres
spring.datasource.password=655797

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql

# THYMELEAF
spring.thymeleaf.cache=false
